server:
  port: 9002
eureka:
  client:
    service-url:
      defaultZone: http://EurekaServerA:8761/eureka,http://EurekaServerB:8762/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
  #分布式链路追踪
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.cloud.sleuth: debug

spring:
  application:
    name: sc-gateway
  zipkin:
    base-url: http://127.0.0.1:9411 # zipkin server的请求地址
    sender:
      # web 客户端将踪迹日志数据通过网络请求的方式传送到服务端，另外还有配 置
      # kafka/rabbit 客户端将踪迹日志数据传递到mq进行中转
      type: web
  sleuth:
    sampler:
      # 采样率 1 代表100%全部采集 ，默认0.1 代表10% 的请求踪迹数据会被采集
      # 生产环境下，请求量非常大，没有必要所有请求的踪迹数据都采集分析，对于网络包括server端压力都是比较大的，可以配置采样率采集一定比例的请求的踪迹 数据进行分析即可
      probability: 1
  cloud:
    gateway:
      routes:
        - id: service-oauth2-router # 我们自定义的路由 ID，保持唯一
          uri: lb://SC-OAUTH2
          predicates:
            - Path=/oauth/**
        - id: service-autodeliver-router # 我们自定义的路由 ID，保持唯一
#          uri: http://127.0.0.1:8090
          uri: lb://SC-AUTODELIVER
          predicates:
            - Path=/autodeliver/**
        - id: service-resume-router
#          uri: http://127.0.0.1:8080
          uri: lb://sc-resume
          predicates:
            - Path=/resume/**
          filters:
            - StripPrefix=1 # 将path中的第一个路径去掉，即去掉resume