server:
  port: 8762
spring:
  application:
    name: shred-eureka-server

eureka:
  instance:
    hostname: EurekaServerB
  # Eureka server 集群中每一个server相对于其他server都是client
  client:
    service-url:
      #集群模式，指向其他的server实例，以逗号分隔
      defaultZone: http://EurekaServerA:8761/eureka
    #集群模式需注册自己，自己作为客户端访问其他的server实例
    register-with-eureka: true
    # 查询获取注册中心的服务信息，自己就是Server，不需要，默认时true，集群模式下使用true
    fetch-registry: true
