server:
  port: 8080
#自定义配置信息用于"/actuator/info"读取
info:
  name: 老王
  age: 100
  phone: 110
#通过下面的配置启用所有的监控端点，默认情况下，这些端点是禁用的;
management:
  endpoints:
    web:
      exposure:
        include: "*"
      endpoint:
        health:
          show-details: always
## 将Client作为服务注册到Server，通过Server来监听项目的运行情况
spring:
  boot:
    admin:
      client:
        url: http://localhost:8081
  ##application实例名
  application:
    name: spring-boot-admin-client