#eureka server
server:
  port: 8762
spring:
  application:
    name: sc-erueka-server #应用名称，会在eureka中作为服务名称

    # eureka 客户端配置（和server交互），Eureka Server 其实也是一个Client
eureka:
  instance:
    hostname: EurekaServerB # 当前Eureka实例的主机名
  client:
    service-url: # 配置客户端锁交互的Eureka Server 的地址
      defaultZone: http://EurekaServerA:8761/eureka
    register-with-eureka: true
    fetch-registry: true

