server:
  port: 8080

person:
  family: sdf
  hobby: [play,code,slep]
  map: {k1:v1,k2:v2}
  id: 111
  name: shred
  pet:
    name: QQ
    type: penguin

third:
  enabled: true
  remoteAddress: 192.168.1.11
acme:
  my-person:
    person:
      first-name: aabb